# Generated by Django 5.1.1 on 2024-09-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accounts_alter_products_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
